# Generated by Django 4.0 on 2022-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sCool_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHOD',
            new_name='Admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10),
        ),
    ]
